#!/usr/bin/env bash
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
echo $$ > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; exit" 15
trap "echo 'Y U no love me?!'" 2
trap "rm /var/run/holbertonscript.pid; exit" 3
while true 
do
    echo "To infinity and beyond"
    sleep 2
done
