#!/usr/bin/env bash
# loops from 1 to 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations
i=0
while ((i<10));
do
	echo "Holberton School"
	if ((i == 3))
	then
		echo "bad luck"
	fi
	if ((i == 7))
	then
		echo "good luck"
	fi
	((i++))
done
